services:
    api:
        build: .
        ports:
            - "1337:1337"
        environment:
            SERVICE_APP_NAME: "rust-web-template"
            SERVICE_APP_VERSION: "0.1.0"
            SERVICE_APP_STAGE: "local"
            SERVICE_APP_HOST: "0.0.0.0"
            SERVICE_APP_PORT: 1337
            SERVICE_APP_LOG_LEVEL: "info"
            SERVICE_OBSERVABILITY_API_KEY_HEADER: "x-honeycomb-team"
            SERVICE_OBSERVABILITY_API_KEY: "unknown"
            SERVICE_OBSERVABILITY_API_INGEST_URL: "https://api.honeycomb.io/api/traces"
