services:
    app:
        build: .
        ports:
            - "1337:1337"
        environment:
            # Application Identifiers
            SERVICE_APP_NAME: ${SERVICE_APP_NAME}
            SERVICE_APP_VERSION: ${SERVICE_APP_VERSION}
            SERVICE_APP_STAGE: ${SERVICE_APP_STAGE}

            # Application Settings
            SERVICE_APP_HOST: ${SERVICE_APP_HOST}
            SERVICE_APP_PORT: ${SERVICE_APP_PORT}
            SERVICE_APP_LOG_LEVEL: ${SERVICE_APP_LOG_LEVEL}

            # Database Settings
            SERVICE_DB_NAME: ${SERVICE_DB_NAME}
            SERVICE_DB_HOST: ${SERVICE_DB_HOST}
            SERVICE_DB_PORT: ${SERVICE_DB_PORT}
            SERVICE_DB_USER: ${SERVICE_DB_USER}
            SERVICE_DB_PASSWORD: ${SERVICE_DB_PASSWORD}
            SERVICE_DB_POOL_MIN_CONNECTIONS: ${SERVICE_DB_POOL_MIN_CONNECTIONS}
            SERVICE_DB_POOL_MAX_CONNECTIONS: ${SERVICE_DB_POOL_MAX_CONNECTIONS}
            SERVICE_DB_IDLE_TIMEOUT_MILLIS: ${SERVICE_DB_IDLE_TIMEOUT_MILLIS}
            SERVICE_DB_AQUIRE_TIMEOUT_MILLIS: ${SERVICE_DB_AQUIRE_TIMEOUT_MILLIS}

            # Observability Settings
            SERVICE_OBSERVABILITY_API_KEY_HEADER: ${SERVICE_OBSERVABILITY_API_KEY_HEADER}
            SERVICE_OBSERVABILITY_API_KEY: ${SERVICE_OBSERVABILITY_API_KEY}
            SERVICE_OBSERVABILITY_API_INGEST_URL: ${SERVICE_OBSERVABILITY_API_INGEST_URL}
    test-db:
        image: mariadb:10.6
        environment:
            MYSQL_ROOT_PASSWORD: "super_secret_password"
            MYSQL_DATABASE: ${SERVICE_DB_NAME}
            MYSQL_USER: ${SERVICE_DB_USER}
            MYSQL_PASSWORD: ${SERVICE_DB_PASSWORD}
        ports:
            - "3303:3306"
