services:
    app:
        build: .
        ports:
            - "1337:1337"
        depends_on:
            - test-db
        environment:
            # Application Identifiers
            SERVICE_APP_NAME: ${SERVICE_APP_NAME}
            SERVICE_APP_VERSION: ${SERVICE_APP_VERSION}
            SERVICE_APP_STAGE: ${SERVICE_APP_STAGE}

            # Application Settings
            SERVICE_APP_HOST: ${SERVICE_APP_HOST}
            SERVICE_APP_PORT: ${SERVICE_APP_PORT}
            SERVICE_APP_LOG_LEVEL: ${SERVICE_APP_LOG_LEVEL}

            # Database Settings
            SERVICE_DB_NAME: ${SERVICE_DB_NAME}
            SERVICE_DB_HOST: test-db # This is the name of the service in the docker-compose file
            SERVICE_DB_PORT: ${SERVICE_DB_PORT} # This is the port of the db inside the container network
            SERVICE_DB_USER: ${SERVICE_DB_USER}
            SERVICE_DB_PASSWORD: ${SERVICE_DB_PASSWORD}
            SERVICE_DB_POOL_MIN_CONNECTIONS: ${SERVICE_DB_POOL_MIN_CONNECTIONS}
            SERVICE_DB_POOL_MAX_CONNECTIONS: ${SERVICE_DB_POOL_MAX_CONNECTIONS}
            SERVICE_DB_IDLE_TIMEOUT_MILLIS: ${SERVICE_DB_IDLE_TIMEOUT_MILLIS}
            SERVICE_DB_AQUIRE_TIMEOUT_MILLIS: ${SERVICE_DB_AQUIRE_TIMEOUT_MILLIS}

            # Observability Settings
            SERVICE_OBSERVABILITY_API_KEY_HEADER: ${SERVICE_OBSERVABILITY_API_KEY_HEADER}
            SERVICE_OBSERVABILITY_API_KEY: ${SERVICE_OBSERVABILITY_API_KEY}
            SERVICE_OBSERVABILITY_API_INGEST_URL: ${SERVICE_OBSERVABILITY_API_INGEST_URL}
    test-db:
        image: postgres:16.4
        environment:
            POSTGRES_DB: ${SERVICE_DB_NAME}
            POSTGRES_USER: ${SERVICE_DB_USER}
            POSTGRES_PASSWORD: ${SERVICE_DB_PASSWORD}
        ports:
            - "5432:5432"
