[package]
name = "gen-api-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal
lib-controller = { path = "../lib/controller" }

# External
utoipa = { workspace = true, features = ["axum_extras"] }
utoipauto = { workspace = true }