// Application Identifiers
pub const APP_NAME: &str = "SERVICE_APP_NAME";
pub const APP_VERSION: &str = "SERVICE_APP_VERSION";
pub const APP_STAGE: &str = "SERVICE_APP_STAGE";

// Application Settings
pub const APP_LOG_LEVEL: &str = "SERVICE_APP_LOG_LEVEL";
pub const APP_HOST: &str = "SERVICE_APP_HOST";
pub const APP_PORT: &str = "SERVICE_APP_PORT";

// Database Settings
pub const DB_NAME: &str = "SERVICE_DB_NAME";
pub const DB_HOST: &str = "SERVICE_DB_HOST";
pub const DB_PORT: &str = "SERVICE_DB_PORT";
pub const DB_USER: &str = "SERVICE_DB_USER";
pub const DB_PASSWORD: &str = "SERVICE_DB_PASSWORD";
pub const DB_POOL_MIN_CONNECTIONS: &str = "SERVICE_DB_POOL_MIN_CONNECTIONS";
pub const DB_POOL_MAX_CONNECTIONS: &str = "SERVICE_DB_POOL_MAX_CONNECTIONS";
pub const DB_IDLE_TIMEOUT_MILLIS: &str = "SERVICE_DB_IDLE_TIMEOUT_MILLIS";
pub const DB_AQUIRE_TIMEOUT_MILLIS: &str = "SERVICE_DB_AQUIRE_TIMEOUT_MILLIS";

// Observability Settings
pub const OBSERVABILITY_API_KEY_HEADER: &str = "SERVICE_OBSERVABILITY_API_KEY_HEADER";
pub const OBSERVABILITY_API_KEY: &str = "SERVICE_OBSERVABILITY_API_KEY";
pub const OBSERVABILITY_API_INGEST_URL: &str = "SERVICE_OBSERVABILITY_API_INGEST_URL";
